#!/bin/sh
#
# ``midilib`` wrapper script
#
#    (c) 2021 Yoichi Tanibayashi
#
MYNAME=`basename $0`
BINDIR="$HOME/bin"

PKG_NAME="midilib"

ENV_FILE="$BINDIR/$PKG_NAME.env"
. $ENV_FILE

export PYGAME_HIDE_SUPPORT_PROMPT=hide

if [ -z $VIRTUAL_ENV ]; then
   if [ -f $VENVDIR/bin/activate ]; then
       . $VENVDIR/bin/activate
   else
       echo
       echo "ERROR(venv): can not activate python3 Virtualenv"
       echo
    exit 1
   fi
fi

exec python -m $PKG_NAME $*

### Local Variables: ***
### mode:shell-script ***
### End: ***
